(() => {
  'use strict';
  const base = new URL('.', document.baseURI);
  const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
  const url = (path) => new URL(path, base);
  const astraUrl = (path) => url(`data/scene-astra/${path}`);
  const interactiveActive = [];
  const astraActive = [];
  const astraIds = ['Gemini_Generated_Image_gkkzzjgkkzzjgkkz', '012_hotel_lobby', 'Gemini_Generated_Image_dfwzixdfwzixdfwz', 'Gemini_Generated_Image_dh6x0wdh6x0wdh6x', '002_bedroom_suite', 'Gemini_Generated_Image_ac4a5mac4a5mac4a'];
  const release = (entry, list, message) => { entry.viewers.forEach((viewer) => viewer?.dispose()); entry.viewers = []; const i = list.indexOf(entry); if (i >= 0) list.splice(i, 1); entry.stages.forEach((stage) => { stage.replaceChildren(); stage.hidden = true; }); entry.status.textContent = message; entry.button.textContent = entry.releaseLabel; entry.button.setAttribute('aria-expanded', 'false'); };

  function initInteractive(host) {
    if (host.dataset.staticGalleryMounted === 'true') return;
    host.dataset.staticGalleryMounted = 'true';
    const status = host.querySelector('.static-gallery-status'); if (!status) return;
    const results = document.createElement('div'); results.className = 'static-results'; results.innerHTML = '<div class="static-scene-grid" aria-live="polite"></div>'; status.replaceWith(results);
    fetch(url('data/mira-scene-results/manifest.json'), { cache: 'no-store' }).then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).then((payload) => { const scenes = payload.cases || []; if (scenes.length !== 12) throw new Error(`Expected 12 cases, found ${scenes.length}`); if (scenes.slice(0, 4).some((scene) => !scene.static_demo) || scenes.slice(4).some((scene) => scene.static_demo)) throw new Error('Expected only the first four cases to include CCM results'); const grid = results.firstElementChild; scenes.forEach((scene, index) => mountInteractiveCard(grid, scene, index)); }).catch((e) => { results.firstElementChild.textContent = `Unable to load interactive results: ${e.message}`; });
  }

  function mountInteractiveCard(host, scene, index) {
    const card = document.createElement('article'); card.className = 'static-scene-card';
    const media = document.createElement('div'); media.className = 'static-scene-card__preview'; const image = document.createElement('img'); image.src = url(scene.thumbnail); image.alt = ''; image.loading = 'lazy'; image.decoding = 'async'; media.append(image);
    const actions = document.createElement('div'); actions.className = 'static-scene-card__actions'; const load = document.createElement('button'); load.type = 'button'; load.className = 'static-scene-card__load'; load.textContent = 'Load interactive 3D scene'; load.setAttribute('aria-expanded', 'false'); actions.append(load);
    if (index < 4 && scene.static_demo) { const link = document.createElement('a'); link.className = 'static-scene-card__demo'; link.href = `static-demo.html?case=${encodeURIComponent(scene.id)}`; link.textContent = 'View CCM workflow →'; actions.append(link); }
    const stage = document.createElement('div'); stage.className = 'static-scene-card__viewer'; stage.hidden = true; const rotation = document.createElement('label'); rotation.className = 'static-scene-card__rotation'; rotation.hidden = true; rotation.append(document.createTextNode('Environment ')); const rotationInput = document.createElement('input'); rotationInput.type = 'range'; rotationInput.min = '-180'; rotationInput.max = '180'; rotationInput.step = '1'; const rotationOutput = document.createElement('output'); rotation.append(rotationInput, rotationOutput); const status = document.createElement('p'); status.className = 'static-scene-card__status'; status.textContent = 'Scene is not loaded.';
    const entry = { viewers: [], stages: [stage], status, button: load, releaseLabel: 'Load interactive 3D scene' };
    load.onclick = async () => { if (entry.viewers.length) return release(entry, interactiveActive, 'Scene is not loaded.'); while (interactiveActive.length >= 6) release(interactiveActive[0], interactiveActive, 'Viewer released · load again'); stage.hidden = false; rotation.hidden = false; status.textContent = 'Initializing 3D viewer…'; load.textContent = 'Release 3D viewer'; load.setAttribute('aria-expanded', 'true'); try { const { StaticStage2Viewer } = await import('./static-stage2-viewer.js'); entry.viewers = [new StaticStage2Viewer(stage, status, scene.id, rotationInput, rotationOutput)]; interactiveActive.push(entry); await entry.viewers[0].load(url(scene.model).href, url(scene.environment).href, scene.method); } catch (e) { if (entry.viewers.length) release(entry, interactiveActive, 'Retry interactive 3D scene'); status.textContent = `Unable to load this scene: ${e.message}`; load.textContent = 'Retry interactive 3D scene'; } };
    card.append(media, actions, rotation, stage, status); host.append(card);
  }

  function makePane(title) {
    const pane = document.createElement('section'); pane.className = 'astra-comparison-pane'; const heading = document.createElement('h4'); heading.className = 'astra-comparison-pane__title'; heading.textContent = title; pane.append(heading); const toolbar = document.createElement('div'); toolbar.className = 'astra-viewer__toolbar'; const cameraLabel = document.createElement('label'); cameraLabel.innerHTML = '<span>View</span>'; const camera = document.createElement('select'); cameraLabel.append(camera); const reset = document.createElement('button'); reset.type = 'button'; reset.textContent = 'Reset view'; const sectionLabel = document.createElement('label'); sectionLabel.innerHTML = '<span>Section height</span>'; const section = document.createElement('input'); section.type = 'range'; section.min = '0'; section.max = '100'; section.value = '100'; sectionLabel.append(section); const wireLabel = document.createElement('label'); const wire = document.createElement('input'); wire.type = 'checkbox'; wireLabel.append(wire, document.createTextNode('Wireframe')); const fullscreen = document.createElement('button'); fullscreen.type = 'button'; fullscreen.textContent = 'Fullscreen'; toolbar.append(cameraLabel, reset, sectionLabel, wireLabel, fullscreen); const stage = document.createElement('div'); stage.className = 'astra-viewer__stage astra-viewer__stage--empty'; stage.innerHTML = `<p>${title} is not loaded.</p>`; const status = document.createElement('div'); status.className = 'astra-viewer__status'; status.setAttribute('role', 'status'); status.textContent = 'No scene selected.'; pane.append(toolbar, stage, status); return { pane, camera, reset, section, wire, fullscreen, stage, status };
  }

  function initAtlas(host) {
    if (host.dataset.astraGalleryMounted === 'true') return;
    host.dataset.astraGalleryMounted = 'true';
    const status = host.querySelector('.astra-results__status'); if (!status) return;
    fetch(url('data/scene-astra/manifest.json'), { cache: 'no-store' }).then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).then((payload) => {
      const byId = new Map((payload.cases || []).map((scene) => [scene.id, scene])); const scenes = astraIds.map((id) => byId.get(id)).filter(Boolean); if (scenes.length !== astraIds.length) throw new Error('Scene Astra manifest is missing selected cases');
      const thumbs = document.createElement('div'); thumbs.className = 'astra-thumbnails'; thumbs.setAttribute('role', 'listbox'); thumbs.setAttribute('aria-label', 'Scene Astra cases'); const viewerPair = document.createElement('div'); viewerPair.className = 'astra-comparison-viewer'; const left = makePane('From Scratch'); const right = makePane('With Mira-Scene'); viewerPair.append(left.pane, right.pane); const entry = { viewers: [], stages: [left.stage, right.stage], status: left.status, button: document.createElement('button'), releaseLabel: 'Load selected scene' }; let current = null; let token = 0;
      const bind = (pane, viewer) => { pane.reset.onclick = () => viewer?.setCamera(viewer.defaultCamera); pane.section.oninput = () => viewer?.setSection(Number(pane.section.value)); pane.wire.onchange = () => viewer?.setWireframe(pane.wire.checked); pane.fullscreen.onclick = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await pane.stage.requestFullscreen(); } catch (e) { pane.status.textContent = `Fullscreen unavailable: ${e.message}`; } }; };
      const select = async (scene, button) => { if (current === scene && entry.viewers.length === 2) return; current = scene; const request = ++token; entry.viewers.forEach((viewer) => viewer?.dispose()); entry.viewers = []; if (!astraActive.includes(entry)) { while (astraActive.length >= 3) release(astraActive[0], astraActive, 'Viewer released · select again'); astraActive.push(entry); } $$('.astra-thumbnail', thumbs).forEach((item) => { item.setAttribute('aria-selected', String(item === button)); item.tabIndex = item === button ? 0 : -1; }); left.stage.replaceChildren(); right.stage.replaceChildren(); left.stage.classList.remove('astra-viewer__stage--empty'); right.stage.classList.remove('astra-viewer__stage--empty'); left.status.textContent = 'Initializing From Scratch viewer…'; right.status.textContent = 'Initializing With Mira-Scene viewer…'; try { const { AstraSceneViewer } = await import('./astra-viewer.js'); if (request !== token) return; const fromScratch = new AstraSceneViewer(left.stage, left.status, left.camera); const withMira = new AstraSceneViewer(right.stage, right.status, right.camera); entry.viewers = [fromScratch, withMira]; bind(left, fromScratch); bind(right, withMira); await Promise.all([fromScratch.load(astraUrl(scene.from_scratch.model).href, scene.from_scratch.model_info), withMira.load(astraUrl(scene.with_mira_scene.model).href, scene.with_mira_scene.model_info)]); } catch (e) { left.status.textContent = `Unable to load From Scratch: ${e.message}`; right.status.textContent = `Unable to load With Mira-Scene: ${e.message}`; } };
      scenes.forEach((scene, index) => { const button = document.createElement('button'); button.className = 'astra-thumbnail'; button.type = 'button'; button.setAttribute('role', 'option'); button.setAttribute('aria-selected', 'false'); button.tabIndex = index ? -1 : 0; button.setAttribute('aria-label', `Scene case ${index + 1}`); const image = document.createElement('img'); image.src = astraUrl(scene.thumbnail); image.alt = ''; image.loading = 'lazy'; image.decoding = 'async'; button.append(image); button.onclick = () => select(scene, button); thumbs.append(button); }); status.replaceWith(thumbs, viewerPair);
    }).catch((e) => { status.textContent = `Unable to load Scene Astra results: ${e.message}`; status.classList.add('astra-results__status--error'); });
  }

  const init = () => { document.querySelectorAll('[data-static-interactive-gallery]').forEach(initInteractive); document.querySelectorAll('[data-astra-gallery]').forEach(initAtlas); };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
  document.addEventListener('mira:content-rendered', init);
  window.addEventListener('pagehide', () => { interactiveActive.slice().forEach((entry) => release(entry, interactiveActive, 'Scene is not loaded.')); astraActive.forEach((entry) => entry.viewers.forEach((viewer) => viewer?.dispose())); });
})();
